name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip3 install -r requirements.txt
    - name: Run tests
      run: python -m pytest -v
    - name: Build the Docker image
      run: |
        echo '${{secrets.HEROKU_API_KEY}}' > civil-hash.json
        docker build . --file Dockerfile --tag tbgc:$(date +%s)
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "tbgc"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true
      env:
        HD_TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        HD_TELEGRAM_CHANNEL_ID: ${{secrets.TELEGRAM_CHANNEL_ID}}
    - name: Clear hash
      if: always()
      run: rm civil-hash.json
